### ISSUE TITLE
fatal error: no original bytecode found in scala.collection.TraversableLike$class.builder$1(Lscala/collection/TraversableLike;Lscala/collection/generic/CanBuildFrom;)Lscala/collection/mutable/Builder; at bci 24

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#204] opened 2016-09-01 20:42 UTC
I'm seeing this error regularly with long-running processes (couple days).  This is the byte code extracted from the core file:

```
  private static final scala.collection.mutable.Builder builder$1(scala.collection.TraversableLike, scala.collection.generic.CanBuildFrom);
    Code:
       0: aload_1       
       1: aload_0       
       2: invokeinterface #72,  1           // InterfaceMethod scala/collection/TraversableLike.repr:()Ljava/lang/Object;
       7: invokeinterface #78,  2           // InterfaceMethod scala/collection/generic/CanBuildFrom.apply:(Ljava/lang/Object;)Lscala/collection/mutable/Builder;
      12: astore_2      
      13: aload_2       
      14: aload_0       
      15: invokeinterface #433,  2          // InterfaceMethod scala/collection/mutable/Builder.sizeHint:(Lscala/collection/TraversableLike;)V
      20: aload_2       
      21: return
```

Also, the bytecode size is correct and there are no breakpoints:

```
(gdb) p this->_constMethod->_code_size
$25 = 22
(gdb) p this->_constMethod->_constants->_pool_holder->_breakpoints 
$26 = (BreakpointInfo *) 0x0
```

The byte at the invalid bci 24 is indeed a breakpoint:

```
(gdb) p (int) *((address) (this->_constMethod+1) + 24)
$27 = 202
```

Unfortunately the `position` argument is optimized out so I have to get all that information from the heap:

```
(gdb) p *debug_info->_handle
$68 = (oop) 0x5d49ebc10
```

Getting object data using the SA:

```
hsdb> inspect 0x5d49ebc10
instance of Oop for jdk/vm/ci/code/DebugInfo @ 0x00000005d49ebc10 @ 0x00000005d49ebc10 (size = 32)
_mark: 1
_metadata._compressed_klass: InstanceKlass for jdk/vm/ci/code/DebugInfo
bytecodePosition: Oop for jdk/vm/ci/code/BytecodeFrame @ 0x00000005d47e3ea0 Oop for jdk/vm/ci/code/BytecodeFrame @ 0x00000005d47e3ea0
referenceMap: Oop for jdk/vm/ci/hotspot/HotSpotReferenceMap @ 0x00000005d49ebe48 Oop for jdk/vm/ci/hotspot/HotSpotReferenceMap @ 0x00000005d49ebe48
virtualObjectMapping: ObjArray @ 0x00000005d47e3fd0 Oop for [Ljdk/vm/ci/code/VirtualObject; @ 0x00000005d47e3fd0
calleeSaveInfo: null null

hsdb> inspect 0x00000005d47e3ea0
instance of Oop for jdk/vm/ci/code/BytecodeFrame @ 0x00000005d47e3ea0 @ 0x00000005d47e3ea0 (size = 48)
_mark: 1
_metadata._compressed_klass: InstanceKlass for jdk/vm/ci/code/BytecodeFrame
caller: Oop for jdk/vm/ci/code/BytecodeFrame @ 0x00000005d47e3e70 Oop for jdk/vm/ci/code/BytecodeFrame @ 0x00000005d47e3e70
method: Oop for jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl @ 0x0000000587ee5af0 Oop for jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl @ 0x0000000587ee5af0
bci: 24
values: ObjArray @ 0x00000005d47e3bc0 Oop for [Ljdk/vm/ci/meta/JavaValue; @ 0x00000005d47e3bc0
slotKinds: ObjArray @ 0x00000005d47e3be0 Oop for [Ljdk/vm/ci/meta/JavaKind; @ 0x00000005d47e3be0
numLocals: 3
numStack: 0
numLocks: 0
rethrowException: false
duringCall: true

hsdb> inspect 0x0000000587ee5af0
instance of Oop for jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl @ 0x0000000587ee5af0 @ 0x0000000587ee5af0 (size = 48)
_mark: 25
_metadata._compressed_klass: InstanceKlass for jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl
name: "builder$1" @ 0x0000000587ee5b20 Oop for java/lang/String @ 0x0000000587ee5b20
metaspaceMethod: 140492136646264
holder: Oop for jdk/vm/ci/hotspot/HotSpotResolvedObjectTypeImpl @ 0x0000000587ee3290 Oop for jdk/vm/ci/hotspot/HotSpotResolvedObjectTypeImpl @ 0x0000000587ee3290
constantPool: Oop for jdk/vm/ci/hotspot/HotSpotConstantPool @ 0x0000000587ee3490 Oop for jdk/vm/ci/hotspot/HotSpotConstantPool @ 0x0000000587ee3490
signature: Oop for jdk/vm/ci/hotspot/HotSpotSignature @ 0x0000000587ee5b60 Oop for jdk/vm/ci/hotspot/HotSpotSignature @ 0x0000000587ee5b60
methodData: Oop for jdk/vm/ci/hotspot/HotSpotMethodData @ 0x0000000587ee5e50 Oop for jdk/vm/ci/hotspot/HotSpotMethodData @ 0x0000000587ee5e50
code: [B @ 0x0000000587ee5e68 Oop for [B @ 0x0000000587ee5e68
toJavaCache: null null

hsdb> inspect 0x0000000587ee3290
instance of Oop for jdk/vm/ci/hotspot/HotSpotResolvedObjectTypeImpl @ 0x0000000587ee3290 @ 0x0000000587ee3290 (size = 48)
_mark: 33
_metadata._compressed_klass: InstanceKlass for jdk/vm/ci/hotspot/HotSpotResolvedObjectTypeImpl
name: "Lscala/collection/TraversableLike$class;" @ 0x0000000587ee32c0 Oop for java/lang/String @ 0x0000000587ee32c0
javaClass: Oop for java/lang/Class @ 0x0000000587ee30a8 Oop for java/lang/Class @ 0x0000000587ee30a8
fieldCache: null null
methodCache: Oop for java/util/HashMap @ 0x0000000587ee3338 Oop for java/util/HashMap @ 0x0000000587ee3338
instanceFields: null null
interfaces: null null
constantPool: Oop for jdk/vm/ci/hotspot/HotSpotConstantPool @ 0x0000000587ee3490 Oop for jdk/vm/ci/hotspot/HotSpotConstantPool @ 0x0000000587ee3490
context: Oop for jdk/vm/ci/hotspot/HotSpotJVMCIMetaAccessContext @ 0x00000005843a4770 Oop for jdk/vm/ci/hotspot/HotSpotJVMCIMetaAccessContext @ 0x00000005843a4770
arrayOfType: null null
```

The method matches so it seems the bci is just wrong.

**Comment by christhalinger** [comment] 2016-09-07 20:43
Running with some debugging code I see this bci-out-of-bounds a lot:

```
java.lang.AssertionError: HotSpotMethod<AtomicInteger.incrementAndGet()>, codeSize = 14, bci = 24
java.lang.AssertionError: HotSpotMethod<HashMap.get(Object)>, codeSize = 12, bci = 24
java.lang.AssertionError: HotSpotMethod<HashMap.containsKey(Object)>, codeSize = 18, bci = 24
```

Interestingly it's always bci 24.

**Comment by dougxc** [comment] 2016-09-08 14:08
Where did you put the debug code? Tom just added an assertion in the FrameState constructor (https://github.com/graalvm/graal-core/commit/5fcf051afda193eca2bf645ec1fdffc921e131e7) that should more close pin point where this is coming from. Could you please try a `GraalError.guarantee` version of his assertion (so you can run without `-esa`) and see if you get a useful stack trace.

**Comment by christhalinger** [comment] 2016-09-08 17:13
It's not really an assert I'm just using `AssertionError` to produce the stack trace (in hindsight that was not a good choice because it's confusing):

```
diff --git a/jvmci/jdk.vm.ci.code/src/jdk/vm/ci/code/BytecodePosition.java b/jvmci/jdk.vm.ci.code/src/jdk/vm/ci/code/BytecodePosition.java
index 1b35f7e..a1f15dd 100644
--- a/jvmci/jdk.vm.ci.code/src/jdk/vm/ci/code/BytecodePosition.java
+++ b/jvmci/jdk.vm.ci.code/src/jdk/vm/ci/code/BytecodePosition.java
@@ -47,6 +47,9 @@ public class BytecodePosition {
      */
     public BytecodePosition(BytecodePosition caller, ResolvedJavaMethod method, int bci) {
         assert method != null;
+        if (!(0 <= bci && bci < method.getCodeSize())) {
+            new AssertionError(method + ", codeSize = " + method.getCodeSize() + ", bci = " + bci).printStackTrace();
+        }
         this.caller = caller;
         this.method = method;
         this.bci = bci;
```

The reason I did it this way is because I need the compilation to continue in order to crash the VM so I can detect it happened more easily.

**Comment by christhalinger** [comment] 2016-09-08 17:14
Oh, I thought I pasted a stack trace already.  Well, here it is:

```
java.lang.AssertionError: HotSpotMethod<AtomicInteger.incrementAndGet()>, codeSize = 14, bci = 24
	at jdk.vm.ci.code.BytecodePosition.<init>(BytecodePosition.java:51)
	at jdk.vm.ci.code.BytecodeFrame.<init>(BytecodeFrame.java:195)
	at com.oracle.graal.compiler.gen.DebugInfoBuilder.computeFrameForState(DebugInfoBuilder.java:215)
	at com.oracle.graal.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:85)
	at com.oracle.graal.compiler.gen.DebugInfoBuilder.build(DebugInfoBuilder.java:93)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.stateForWithExceptionEdge(NodeLIRBuilder.java:723)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.stateWithExceptionEdge(NodeLIRBuilder.java:711)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.emitInvoke(NodeLIRBuilder.java:586)
	at com.oracle.graal.nodes.InvokeNode.generate(InvokeNode.java:153)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:451)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:441)
	at com.oracle.graal.compiler.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:359)
	at com.oracle.graal.compiler.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:80)
	at com.oracle.graal.compiler.LIRGenerationPhase.run(LIRGenerationPhase.java:67)
	at com.oracle.graal.compiler.LIRGenerationPhase.run(LIRGenerationPhase.java:43)
	at com.oracle.graal.lir.phases.LIRPhase.apply(LIRPhase.java:121)
	at com.oracle.graal.lir.phases.LIRPhase.apply(LIRPhase.java:114)
	at com.oracle.graal.compiler.GraalCompiler.emitLIR0(GraalCompiler.java:295)
	at com.oracle.graal.compiler.GraalCompiler.emitLIR(GraalCompiler.java:250)
	at com.oracle.graal.compiler.GraalCompiler.emitBackEnd(GraalCompiler.java:230)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:176)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:162)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:136)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:212)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:393)
```

**Comment by dougxc** [comment] 2016-09-08 19:47
Can you please try the same trick but put the check in the `FrameState` constructor (as well).

**Comment by christhalinger** [comment] 2016-09-08 19:55
Yes.  It will take me a while to deploy this.

**Comment by dougxc** [comment] 2016-09-08 21:04
Ok, thanks for your help.

**Comment by christhalinger** [comment] 2016-09-09 20:14
Here is the `FrameState` backtrace:

```
java.lang.AssertionError: HotSpotMethod<Short.parseShort(String)>, codeSize = 7, bci = 24
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:123)
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:149)
	at com.oracle.graal.nodes.FrameState.duplicateModified(FrameState.java:378)
	at com.oracle.graal.nodes.FrameState.duplicateModifiedDuringCall(FrameState.java:313)
	at com.oracle.graal.nodes.Invoke.computeStateDuring(Invoke.java:94)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:83)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:57)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:115)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:98)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase.run(FrameStateAssignmentPhase.java:119)
	at com.oracle.graal.phases.Phase.run(Phase.java:51)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:206)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:175)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:162)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:136)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:212)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:393)
```

**Comment by christhalinger** [comment] 2016-09-09 20:54
Turns out that the https://github.com/mariusae/heapster agent is causing the problem.  I could reproduce it locally with:

```
$ git clone https://github.com/mariusae/heapster
...
~/heapster$ make
...
~/jvmci$ cp ~/heapster/libheapster.dylib build/macosx-x86_64-normal-server-release/images/j2sdk-image/jre/lib/
~/jvmci$ ./build/macosx-x86_64-normal-server-release/images/j2sdk-image/bin/java -XX:+EnableJVMCI -XX:+UseJVMCICompiler -Dgraal.CompilerConfiguration=enterprise -XX:+BootstrapJVMCI -agentlib:heapster -version
Bootstrapping JVMCI................java.lang.AssertionError: HotSpotMethod<Node.hashCode()>, codeSize = 5, bci = 24
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:123)
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:149)
	at com.oracle.graal.nodes.FrameState.duplicateModified(FrameState.java:378)
	at com.oracle.graal.nodes.FrameState.duplicateModifiedDuringCall(FrameState.java:313)
	at com.oracle.graal.nodes.Invoke.computeStateDuring(Invoke.java:94)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:83)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:57)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:115)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.processLoop(ReentrantNodeIterator.java:81)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processLoop(FrameStateAssignmentPhase.java:111)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processLoop(FrameStateAssignmentPhase.java:57)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:132)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.processLoop(ReentrantNodeIterator.java:81)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processLoop(FrameStateAssignmentPhase.java:111)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processLoop(FrameStateAssignmentPhase.java:57)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:132)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:98)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase.run(FrameStateAssignmentPhase.java:119)
	at com.oracle.graal.phases.Phase.run(Phase.java:51)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:206)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:175)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:162)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:136)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:212)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:393)
```

**Comment by christhalinger** [comment] 2016-09-10 00:02
FTR, I can also reproduce it with `graal-jvmci-8`:

```
cthalinger@tw-mbp-cthalinger:~/graalvm/graal-jvmci-8$ ./jdk1.8.0_72/product/bin/java -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+BootstrapJVMCI -agentlib:heapster -version
Bootstrapping JVMCI..............java.lang.AssertionError: HotSpotMethod<InliningUtil.printInlining(InlineInfo, int, boolean, String, Object[])>, codeSize = 22, bci = 24
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:124)
	at com.oracle.graal.nodes.FrameState.<init>(FrameState.java:150)
	at com.oracle.graal.nodes.FrameState.duplicateModified(FrameState.java:379)
	at com.oracle.graal.nodes.FrameState.duplicateModifiedDuringCall(FrameState.java:314)
	at com.oracle.graal.nodes.Invoke.computeStateDuring(Invoke.java:94)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:83)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase$FrameStateAssignmentClosure.processNode(FrameStateAssignmentPhase.java:57)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:115)
	at com.oracle.graal.phases.graph.ReentrantNodeIterator.apply(ReentrantNodeIterator.java:98)
	at com.oracle.graal.phases.common.FrameStateAssignmentPhase.run(FrameStateAssignmentPhase.java:119)
	at com.oracle.graal.phases.Phase.run(Phase.java:51)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.phases.PhaseSuite.run(PhaseSuite.java:154)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:170)
	at com.oracle.graal.phases.BasePhase.apply(BasePhase.java:154)
	at com.oracle.graal.compiler.GraalCompiler.emitFrontEnd(GraalCompiler.java:206)
	at com.oracle.graal.compiler.GraalCompiler.compile(GraalCompiler.java:175)
	at com.oracle.graal.compiler.GraalCompiler.compileGraph(GraalCompiler.java:162)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:136)
	at com.oracle.graal.hotspot.CompilationTask.runCompilation(CompilationTask.java:212)
	at com.oracle.graal.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:93)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:409)
```

**Comment by dougxc** [comment] 2016-09-12 14:08
As I suspected, the problem is that we don't isolate snippet bytecode from instrumentation agents. In this case, it's the bytecode of `Double.valueOf` inlined into `com.oracle.graal.replacements.BoxingSnippets.doubleValueOf(double)`.

**Comment by tkrodriguez** [comment] 2016-09-12 15:08
This isn't even code that we own so we don't have a good way around this.  I think the assert in ReplacementsImpl.notifyNotInlined should be raised to a hard error since it was masking this issue.  We might also need more checks in snippet handling in general so that this kind of misassociation of bci and method doesn't happen in other places.

**Comment by dougxc** [comment] 2016-09-12 15:17
I think it's time to bite the bullet and parse the bytecodes for snippets (and their callees) directly. I'm looking into the best way to do this.

**Comment by tkrodriguez** [comment] 2016-09-19 23:46
This problem should now cause a hard error https://github.com/graalvm/graal-core/commit/8f7caf5324954da72b7cebc303375d435fffb8ac

Should we proactively detect bad boxing snippets and disable the boxing optimization for them?

**Comment by dougxc** [comment] 2016-09-20 08:29
No - I'm currently working on a solution for isolating parsing of snippets from bytecode transformations.

**Comment by dougxc** [comment] 2016-09-28 12:14
This should now be fixed by https://github.com/graalvm/graal-core/commit/d5bf8b6b623f0c6b8c6998cfee544a61398c7322. Can you please verify @christhalinger and then close this issue.

**Closed** 2016-10-11 09:36 UTC

**Comment by christhalinger** [comment] 2016-10-11 20:02
Sorry, didn't have time to verify.  Still on my TODO list...

**Comment by christhalinger** [comment] 2017-05-12 19:52
Wow, that took a long time but we are not seeing this anymore.  Closed.
