### ISSUE TITLE
fatal error: jvmtifiles/jvmti.h: No such file or directory

### ISSUE THREAD

**Issue by noahdesu** [graalvm/graal-core#137] opened 2016-03-16 23:47 UTC
With the latest master I am building with `mx build` using Java 1.8 and the server vm. The build hits this error, but seems to continue on successfully. Is this something I should be concerned about?

```
Generating precompiled header precompiled.hpp.gch
In file included from /home/nwatkins/src/astos/jvmci/src/os_cpu/linux_x86/vm/atomic_linux_x86.inline.hpp:29:0,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/runtime/atomic.inline.hpp:32,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/memory/allocation.inline.hpp:28,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/utilities/array.hpp:29,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/memory/universe.hpp:29,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/code/oopRecorder.hpp:28,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/asm/codeBuffer.hpp:28,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/asm/assembler.hpp:28,

                 from /home/nwatkins/src/astos/jvmci/src/share/vm/precompiled/precompiled.hpp:29:

/home/nwatkins/src/astos/jvmci/src/share/vm/runtime/os.hpp:28:30: fatal error: jvmtifiles/jvmti.h: No such file or directory

compilation terminated.

/home/nwatkins/src/astos/jvmci/make/linux/makefiles/vm.make:321: recipe for target 'precompiled.hpp.gch' failed
make[4]: Leaving directory '/home/nwatkins/src/astos/jvmci/build/linux/linux_amd64_compiler2/product'
make[4]: *** [precompiled.hpp.gch] Error 1
```

**Comment by tkrodriguez** [comment] 2016-03-17 02:07
This seems to be a problem with the hotspot makefiles themselves and since it doesn't cause the build to fail presumably it hasn't been noticed/fixed there.  There is a fixed bug with similar symptoms https://bugs.openjdk.java.net/browse/JDK-8017561 but we have that changeset and still see the problem.  I also don't really understand how it's supposed to address the described problem.

I think there's a missing real dependence between generation of the jvmti files and generation of the precompiled headers.  I've never been able to reproduce this reliably enough to debug it.  Are you on centos or a related distro like RHEL or OEL by any chance?

**Comment by tkrodriguez** [comment] 2016-03-17 03:07
I was reminded that I'd seen this on a centos image I'd created and was able to fix it.  I'm pushing a fix to jvmci now and filed a bug about it.  https://bugs.openjdk.java.net/browse/JDK-8152067.

**Comment by noahdesu** [comment] 2016-03-17 05:32
@tkrodriguez i'm on fedora 23. a fix for centos/rhel is probably applicable. thanks! i'll wait for that to land and give it another shot.

**Comment by tkrodriguez** [comment] 2016-03-18 17:04
Try again with latest graal-core.  My Makefile patch is in jvmci and graal-core has been updated to use the latest version.

**Comment by tkrodriguez** [comment] 2016-03-23 21:43
I'm closing this as fixed.  Reopen it if it's not actually working for you.

**Closed by tkrodriguez** 2016-03-23 21:43 UTC
