### ISSUE TITLE
Netty 4.1.5 tests fail

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#206] opened 2016-09-09 23:47 UTC
Today we narrowed down where these odd connection exceptions we were seeing are coming from:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [  5.584 s]
[INFO] Netty/Common ....................................... SUCCESS [01:15 min]
[INFO] Netty/Buffer ....................................... FAILURE [ 48.142 s]
```

I downloaded https://github.com/netty/netty/archive/netty-4.1.5.Final.tar.gz and ran `mvn test` first with C2 and then with Graal.  A C2 run finishes successfully:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [  7.284 s]
[INFO] Netty/Common ....................................... SUCCESS [ 55.825 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 49.838 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  3.506 s]
[INFO] Netty/Transport .................................... SUCCESS [ 50.733 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 17.517 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  4.326 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  4.008 s]
[INFO] Netty/Handler ...................................... SUCCESS [ 16.036 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [ 11.036 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 17.606 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  4.197 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  4.140 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  4.110 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  3.740 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  5.091 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  3.873 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  4.529 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  9.881 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  1.482 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  1.849 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [ 18.853 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [ 13.376 s]
[INFO] Netty/Example ...................................... SUCCESS [  4.912 s]
[INFO] Netty/Testsuite .................................... SUCCESS [19:05 min]
[INFO] Netty/Testsuite/OSGI ............................... SUCCESS [01:15 min]
[INFO] Netty/Transport/Native/Epoll ....................... SUCCESS [05:58 min]
[INFO] Netty/Microbench ................................... SUCCESS [ 16.383 s]
[INFO] Netty/All-in-One ................................... SUCCESS [  0.078 s]
[INFO] Netty/Tarball ...................................... SUCCESS [  0.168 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:54 min
[INFO] Finished at: 2016-09-09T16:24:39-07:00
[INFO] Final Memory: 216M/6323M
[INFO] ------------------------------------------------------------------------
```

Add the Graal options to `pom.xml` here:

```
    <argLine.common>
      -server
      -dsa -da -ea:io.netty...
      -XX:+AggressiveOpts
      -XX:+TieredCompilation
      -XX:+UseBiasedLocking
      -XX:+UseFastAccessorMethods
      -XX:+OptimizeStringConcat
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:+EnableJVMCI
      -XX:+UseJVMCICompiler
    </argLine.common>
```

**Comment by christhalinger** [comment] 2016-09-12 17:38
The first errors are:

```
Tests run: 266, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.443 sec <<< FAILURE! - in io.netty.buffer.LittleEndianUnsafeDirectByteBufTest
testSequentialUnsignedShortAccess(io.netty.buffer.LittleEndianUnsafeDirectByteBufTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected:<9110> but was:<38435>

testSequentialUnsignedShortLEAccess(io.netty.buffer.LittleEndianUnsafeDirectByteBufTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected:<21827> but was:<17237>
```

All of them look related to `io.netty.buffer`.

**Comment by christhalinger** [comment] 2016-09-12 17:53
I was able to reproduce the failure when bootstrapping:

```
cthalinger@buildbot:~/netty-netty-4.1.5.Final$ ~/jvmci/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+BootstrapJVMCI -cp ~/.m2/repository/junit/junit/4.12/junit-4.12.jar:$HOME/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:$HOME/.m2/repository/org/jctools/jctools-core/1.2.1/jctools-core-1.2.1.jar:./common/target/classes/:./buffer/target/classes/:./buffer/target/test-classes/ org.junit.runner.JUnitCore io.netty.buffer.LittleEndianUnsafeDirectByteBufTest
Bootstrapping JVMCI........................... in 7923 ms (compiled 2794 methods)
JUnit version 4.12
....................................................................................................................................................E....................................E..................................................................................
Time: 1.237
There were 2 failures:
1) testSequentialUnsignedShortAccess(io.netty.buffer.LittleEndianUnsafeDirectByteBufTest)
java.lang.AssertionError: expected:<60628> but was:<54508>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.netty.buffer.AbstractByteBufTest.testSequentialUnsignedShortAccess(AbstractByteBufTest.java:796)
	at io.netty.buffer.AbstractByteBufTest.testSequentialUnsignedShortAccess(AbstractByteBufTest.java:765)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
2) testSequentialUnsignedShortLEAccess(io.netty.buffer.LittleEndianUnsafeDirectByteBufTest)
java.lang.AssertionError: expected:<16949> but was:<13634>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.netty.buffer.AbstractByteBufTest.testSequentialUnsignedShortAccess(AbstractByteBufTest.java:796)
	at io.netty.buffer.AbstractByteBufTest.testSequentialUnsignedShortLEAccess(AbstractByteBufTest.java:770)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 266,  Failures: 2
```

**Comment by tkrodriguez** [comment] 2016-09-12 18:16
[9/12/16, 11:07:31 AM] Tom Rodriguez: we seem to be writing the values with the wrong endianness.
[9/12/16, 11:07:39 AM] Tom Rodriguez: java.lang.AssertionError: expected:<54694> but was:<42709>
[9/12/16, 11:07:46 AM] Tom Rodriguez: $ tohex 42709
a6d5
$ tohex 54694
d5a6

**Comment by tkrodriguez** [comment] 2016-09-12 23:42
The problem is that the reverseBytes plugins for short and char do incorrect canonicalization that may eliminate that reverse completely.

**Comment by tkrodriguez** [comment] 2016-09-15 01:47
resolved in https://github.com/graalvm/graal-core/commit/4e669843a07171a538bd53e4fd5e7c57d13b2eca

**Closed by tkrodriguez** 2016-09-15 01:47 UTC
