### ISSUE TITLE
Graal should support same OSR compilations as C1 and C2

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#128] opened 2016-03-14 19:02 UTC
While running some obfuscated code I see a lot of these:

```
 250398 21839 %s!   4       ge::al @ 1586 (2018 bytes)   COMPILE SKIPPED: OSR with locks not supported
```

@tkrodriguez took a brief look and it seems the only OSR compilations that C1 and C2 don't support is non-empty stack at OSR.

**Comment by christhalinger** [comment] 2016-03-14 19:16
I'm seeing similar bailouts with jorbis:

  31342 22854 %s    4       com.jcraft.jorbis.Mdct::backward @ 103 (468 bytes)   COMPILE SKIPPED: OSR with locks not supported
  31529 22856 %s    4       com.jcraft.jorbis.Mapping0::inverse @ 804 (867 bytes)   COMPILE SKIPPED: OSR with locks not supported

**Comment by christhalinger** [comment] 2016-03-14 23:21
This is an interesting and possibly important one:

   4045 13616 % !   4       java.util.concurrent.ConcurrentHashMap::transfer @ 376 (832 bytes)   COMPILE SKIPPED: OSR with locks not supported

**Comment by dougxc** [comment] 2016-09-15 19:30
@christhalinger , you interested in having a go at this?

**Comment by christhalinger** [comment] 2016-09-15 19:34
Interested?  Yes.  Do I have time right now?  No.

**Comment by dougxc** [comment] 2017-03-22 13:36
@christhalinger , this should be fixed as of https://github.com/graalvm/graal-core/commit/34dc32c. Can you please confirm this works on your end.

**Comment by christhalinger** [comment] 2017-03-22 19:14
Oh, sweet!  Let me give this a go...

**Comment by christhalinger** [comment] 2017-03-23 20:09
It looks like it's working fine now.  I tried Runescape and didn't see any OSR errors.  But as I understand it Runescape is downloading jar files so the code might not be the same.

Then I tried Jorbis (with https://commons.wikimedia.org/w/index.php?title=File%3ARondo_Alla_Turka.ogg) and that seems to be fine too:

```
$ java -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+PrintCompilation -cp ..:. JOrbisPlayer Rondo_Alla_Turka.ogg | tee log.txt
...
$ cat log.txt | grep com.jcraft.jorbis.Mdct::backward
   5670 4479 %s    4       com.jcraft.jorbis.Mdct::backward @ 100 (468 bytes)
$ cat log.txt | grep com.jcraft.jorbis.Mapping0::inverse
   5510 4112 %s    3       com.jcraft.jorbis.Mapping0::inverse @ 808 (867 bytes)
   5512 4113 %s    3       com.jcraft.jorbis.Mapping0::inverse @ 523 (867 bytes)
   5517 4139 %s    3       com.jcraft.jorbis.Mapping0::inverse @ 239 (867 bytes)
   5520 4146 %s    4       com.jcraft.jorbis.Mapping0::inverse @ 808 (867 bytes)
   5549 4112 %s    3       com.jcraft.jorbis.Mapping0::inverse @ -2 (867 bytes)   made not entrant
   5657 4459 %s    4       com.jcraft.jorbis.Mapping0::inverse @ 239 (867 bytes)
   5831 4139 %s    3       com.jcraft.jorbis.Mapping0::inverse @ -2 (867 bytes)   made not entrant
   5927 4868  s    4       com.jcraft.jorbis.Mapping0::inverse (867 bytes)
   5949 4112 %s    3       com.jcraft.jorbis.Mapping0::inverse @ -2 (867 bytes)   made zombie
  29476 4139 %s    3       com.jcraft.jorbis.Mapping0::inverse @ -2 (867 bytes)   made zombie
```

The BCIs are slightly off but I blame javac for that.  The byte code sizes of the methods are at least the same.

Next I will try one of our services because I'm seeing the same issue there too:

```
Bailout in sun.management.counter.perf.PerfInstrumentation.findByPattern(String)
jdk.vm.ci.code.BailoutException: OSR with locks not supported
```

**Comment by christhalinger** [comment] 2017-03-24 21:38
The one's I've seen before are fixed but now I'm seeing these:

```
$ cat graal.log | grep -B1 BailoutException
Bailout in net.reduls.gomoku.dic.Morpheme.<clinit>()
org.graalvm.compiler.common.PermanentBailoutException: No OnStackReplacementNode generated
--
Bailout in net.reduls.gomoku.dic.Matrix.<clinit>()
org.graalvm.compiler.common.PermanentBailoutException: No OnStackReplacementNode generated
--
Bailout in java.util.concurrent.atomic.AtomicBoolean.getAndSet(boolean)
org.graalvm.compiler.common.PermanentBailoutException: OSR compilation without OSR entry loop.
```

**Comment by tkrodriguez** [comment] 2017-03-27 18:43
Any chance you can provide graphs for the last one?

For the first two it looks like the parse didn't reach the OSR point which suggests we're trimming control flow for some reason.  I grabbed a copy of gomoku and ran it locally and it appears to be a problem with deoptimizing on static field access in the clinit.  There's a little piece of logic in C2's parser which allows access to static fields within the clinit for classes which aren't fully initialized yet.  http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/opto/parse3.cpp#l42 
 I think we need a copy of that logic in the BytecodeParser.  I'll create an issue for that.

**Comment by tkrodriguez** [comment] 2017-03-27 18:45
https://github.com/graalvm/graal-core/issues/263

**Comment by christhalinger** [comment] 2017-03-30 17:57
Yes, I can get you the graph for `java.util.concurrent.atomic.AtomicBoolean.getAndSet(boolean)`.

**Comment by christhalinger** [comment] 2017-09-05 21:34
Did I send you the graph?

**Comment by tkrodriguez** [comment] 2017-09-06 17:00
No I don't think so.  Does this still reproduce?

**Comment by tkrodriguez** [comment] 2018-04-16 18:29
The getAndSet issue was reproduced in another context.  Basically C1 profiling is doing something weird and causing an OSR for something that's never taken a backedge.  https://bugs.openjdk.java.net/browse/JDK-8201447 This was fixed by add a workaround in the parser https://github.com/oracle/graal/commit/5944abaae4514e3cda41b504d5ae513f8cab7b0d

**Closed by tkrodriguez** 2018-04-16 18:29 UTC
Labels: oracle-emp
